<div align="center">
    <img src="images/zb-logo.png" alt="제로베이스" width="100%">
    <br>
    <a href="https://zerobaseschool.notion.site/DS-EDA-Lv-Test-b7d5e895c7cd4dda813c8fe2f2c23f79"><img src="images/openinnotion_logo.png" alt="EDA Lv Test Doc" width="12%"></a>

이 Jupyter Notebook 파일은 <a href="https://zero-base.co.kr/category_data_camp/school_DS">제로베이스</a>에서 제공하는 **EDA Level Test** 문제입니다.<br>
지금까지 공부하신 내용으로 데이터 분석에 대해 좀 더 연습할 수 있는 시간이 되셨으면 좋겠습니다.🙂<br>
**EDA Level Test**에 대한 안내 사항은 상단 **Open in ZeroBase Notion** 로고를 클릭하여 확인해주세요!<br>
반드시 시작 전에 내용을 숙지해주시기를 바랍니다!<br>
</div>

***

<h1 style="background-color:#9F81F7;color:#D8D8D8;font-weight:bold;display:inline-block;padding: 5px">EDA Level Test 02 ⭐️⭐️⭐️</h1>

| Week | Data Analysis | Difficulty | This Notebook |
|------|---------------|------------|-------|
| 1    | 서울시 인구 데이터 | ⭐️ ||
| 2    | 화장품 성분 데이터 | ⭐️⭐️⭐️ |👈|
| 3    | 올림픽 데이터 | ⭐️⭐️ ||
| 4    | 국가별 인터넷 사용률 데이터 |⭐️⭐️ ||
| 5    | 전국 박물관/미술관 정보 표준 데이터 | ⭐️⭐️⭐️ ||
| 6    | 서울시 흡연율 통계 데이터 | ⭐️⭐️ ||
| 7    | 웹크롤링 | ⭐️ ||
| 8    | 서울시 지하철 호선별 역별 유/무임 승하차 인원 정보 데이터 | ⭐️⭐️ ||
| 9    | 서울시 교통사고 현황 (사고유형별) 통계 데이터 | ⭐️⭐️ ||
| 10   | 서울시 교통사고 현황 (사고유형별) 통계 + 서울시 차량통행속도 (구별/월별) 통계 + 서울시 인구밀도 (구별) 통계 | ⭐️⭐️⭐️ ||

## 문제 소개 및 데이터 준비 단계
- 해당 EDA Level TEST는 기업연계프로젝트 실무 사례 중 일부분입니다.
- 따라서, 난이도가 조금 있을 수 있습니다.
- 이점 참고하시어, 학습에 도움이 되셨으면 좋겠습니다 🙂

<div style="border: 1px solid black; padding: 10px;">

- 총 3단계 데이터 분석 상황 제시
    - 총점 100점
<br></br>
- 1단계 DataFrame 불러오기 & 기초 전처리
- 2단계 전처리
- 3단계 Mapping

### 데이터 원본 출처

#### Target Data(CSV): 화장품의 종류, 브랜드, 제품명, 성분명 등이 포함된 csv 파일
- Source: [Kaggle](https://www.kaggle.com/datasets/kingabzpro/cosmetics-datasets)
- DownLoad: [archive.zip](https://www.kaggle.com/datasets/kingabzpro/cosmetics-datasets/download)

#### 성분 사전: 화장품 전성분의 한글명, 표준영문명, 구명칭, 구 영문명이 포함된 pdf 파일
- Source: [대한 화장품협회](https://kcia.or.kr/cid/search/ingd_list.php?skind=ALL&sword=Lactobacillus%2FCornus+Officinalis+Fruit%2FAngelica+&sword2=)
- DownLoad: [별첨1. 표준화명칭목록_220530.pdf](https://kcia.or.kr/cid/files/%ED%91%9C%EC%A4%80%ED%99%94%EB%AA%85%EC%B9%AD%EB%AA%A9%EB%A1%9D)

### 참고사항
- pdf를 Pandas DataFrame으로 변환하기 위해 Tabula 등의 Library를 사용할 수 있음.
- 혹, 설치시 오류가 발생하거나 코드 실행에 어려움을 겪을 경우 해당 pdf를 읽어 만든 pickle 파일 제공(ingredients_list.pkl)
- 해당 pickle파일은 List형태로 되어 있으며, List 내의 Elements는 각 페이지별 표가 dataframe 형태로 되어 있음
    - ex: [df1, df2, df3, ...]

</div>

In [1]:
import pandas as pd
# 채점을 위한 코드입니다. 반드시 실행해주세요.
from grading import *

df_target = pd.read_csv('./datas/cosmetics.csv')
df_target = df_target.iloc[:5] # 5개의 row만 사용합니다
df_target

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae (Seaweed) Extract, Mineral Oil, Petrolat...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate (Pitera), Butyle...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae (Seaweed) Extract, Cyclopentasiloxane, P...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1

### PDF 파일에 담긴 정보를, 파이썬으로 불러와서 작업하고 싶은 상황!
- 화장품 성분 데이터 분석을 하고 싶은데..
- 잘 정리된 파일을 찾았는데 그게 PDF파일인 경우!

### PDF 파일 내용 확인
- 직접 열어서 꼭 확인해보세요 ^^
- 성분사전 표준화명칭목록 데이터
    - 성분코드
    - 표준 성분명
    - 표준 영문명
    - 구명칭
    - 구영문명
- 총 1460page, 23249만개 데이터
<img src="./images/pdf_01.png" style="margin:auto" width="100%">

### 작업절차
- 파이썬으로 PDF 파일을 읽은 후, pickle 이라는 포맷의 데이터로 저장합니다.
    - 파이썬으로 PDF 파일을 읽기 위해 필요한 모듈
        - `pip install tabula-py`
    - pickle 파일이란?
        - pickle은 파이썬에서 사용하는 딕셔너리, 리스트, 클래스 등의 자료형을 변환 없이 그대로 파일로 저장하고 이를 불러올 때 사용하는 모듈
        - 설명출처: https://wikidocs.net/110788

In [2]:
# !pip install tabula-py

In [3]:
import tabula
import pickle

# Tabula로 PDF 읽기 -> DataFrame List
ingredients_list = tabula.read_pdf('./datas/별첨1. 표준화명칭목록_220530.pdf', pages='all', lattice=True)

# DataFrame List를 Pickle로 저장
with open('./datas/ingredients_list.pkl', 'wb') as f:
    pickle.dump(ingredients_list, f)

#### tabula 실행이 안됩니다!!!
<a href="https://zerobaseschool.notion.site/DS-EDA-Lv-Test-b7d5e895c7cd4dda813c8fe2f2c23f79"><img src="images/openinnotion_logo.png" alt="EDA Lv Test Doc" width="12%"></a> 에서 TroubleShooting ➡️ EDA Level Test 02 tabula module error 부분 확인

- 위 문서 절차대로 진행해도 오류가 발생하시는 분들은, 지금 단계를 생략 해주세요
- 아래 문제 시작 부분부터 진행하시면 됩니다!

## 문제 시작! 🏃🏻

## 1단계: 성분사전 불러오기 & DataFrame 합치기, 수정하기
***

##### Load Pickle File
- Load: Pickle
- List to DataFrame: Pandas

### 위 데이터 준비 단계에서 에러가 발생하시는 분들은, 지금 단계부터 시작해주시면 됩니다!

In [4]:
# from google.colab import drive
# drive.mount('/content/drive')

In [5]:
# Pickle File 불러오기
# import pickle

# with open('/content/drive/MyDrive/제로베이스/EDA_Level_Test_02 (배포용)/datas/ingredients_list.pkl', 'rb') as f:
#     ingredients_list_pkl = pickle.load(f)

### **문제 1-1)** 성분사전 DataFrame 만들기(10점)
- Pickle을 이용해 Load한 ingredients_list_pkl를 하나의 DataFrame으로 합치세요.
<br></br>
    - 조건1: 데이터는 index 기준으로 합치세요.
<br></br>
    - 조건2: join없이 단순히 합치세요.
<br></br>
<br></br>
    - hint1: 20375개의 행이 만들어져야 합니다.
<br></br>
    - hint2: ingredients_list_pkl는 여러 DataFrame들이 Element로 들어있는 List입니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_01 함수에 입력하여 채점하세요.

In [6]:
ingredients_list

[    성분코드         표준 성분명                                      표준 영문명       구명칭  \
 0      1           가공소금                                         NaN       NaN
 1      2        가지열매추출물  Solanum Melongena (Eggplant) Fruit Extract     가지추출물
 2      3       구멍쇠미역추출물                    Agarum Cribrosum Extract  구멍쇠미역추출물
 3      4         루핀아미노산                          Lupine Amino Acids       NaN
 4      5             류신                                     Leucine       NaN
 5      6   류코노스톡/무발효여과물    Leuconostoc/Radish Root Ferment Filtrate       NaN
 6      7         백혈구추출물                           Leukocyte Extract  류코사이트추출물
 7      8  리나칸투스 콤무니스추출물               Rhinacanthus Communis Extract       NaN
 8      9            리날룰                                    Linalool       NaN
 9     10       리날릴아세테이트                             Linalyl Acetate       NaN
 10    11        리놀레닉애씨드                              Linolenic Acid       NaN
 11    12    리놀레아마이드엠이에이                             Linoleamide MEA       NaN

                                           구영문명
 0                                          NaN
 1   Solanum Melongena (Eggplant) Fruit Extract
 2                      Agarum Cribosum Extract
 3                                          NaN
 4                                          NaN
 5                                          NaN
 6                            Leukocyte Extract
 7                                          NaN
 8                                          NaN
 9                                          NaN
 10                                         NaN
 11                                         NaN  ,
     성분코드                             표준 성분명  \
 0     13                            구상나무잎가루
 1     14         리놀레아미도프로필다이메틸아민다이머다이리놀리에이트
 2     15              리놀레아미도프로필에틸다이모늄에토설페이트
 3     16         리놀레아미도프로필피지-다이모늄클로라이드포스페이트
 4     17  리놀레아미도프로필피지-다이모늄클로라이드포스페이트다\r이메티콘
 5     18                            리놀레익애씨드
 6     19                            리마콩씨추출물
 7     20                                리모넨
 8     21                     리모니아 아키디시마목부가루
 9     22                              리보플라빈
 10    23                           구상나무잎추출물
 11    24                             리씨열매오일
 12    25                            리치과피추출물
 13    26                             리치씨추출물

                                                표준 영문명  \
 0                           Abies Koreana Leaf Powder
 1   Linoleamidopropyl Dimethylamine Dimer Dilinoleate
 2         Linoleamidopropyl Ethyldimonium Ethosulfate
 3    Linoleamidopropyl PG-Dimonium Chloride Phosphate
 4   Linoleamidopropyl PG-Dimonium Chloride Phospha...
 5                                       Linoleic Acid
 6         Phaseolus Lunatus (Green Bean) Seed Extract
 7                                            Limonene
 8                      Limonia Acidissima Wood Powder
 9                                          Riboflavin
 10                         Abies Koreana Leaf Extract
 11                            Litsea Cubeba Fruit Oil
 12                  Litchi Chinensis Pericarp Extract
 13                      Litchi Chinensis Seed Extract

                                 구명칭  \
 0                               NaN
 1          리놀레아미도프로필디메칠아민다이머디리놀리에이트
 2              리놀레아미도프로필에칠디모늄에토설페이트
 3         리놀레아미도프로필피지-디모늄클로라이드포스페이트
 4   리놀레아미도프로필피지-디모늄클로라이드포스페이트디메\r치콘
 5                               NaN
 6                            리마콩추출물
 7                               NaN
 8                    리모니아 아시디씨마나무가루
 9                               NaN
 10                              NaN
 11                              NaN
 12                              NaN
 13                              NaN

                                                  구영문명
 0                                                 NaN
 1   Linoleamidopropyl Dimethylamine Dimer Dilinoleate
 2         Linoleamidopropyl Ethyldimonium Ethosulfate
 3    Linoleamidopropyl PG-Dimonium Chloride Phosphate
 4   Linoleamidopropyl PG-Dimonium Chloride Phospha...
 5                                                 NaN
 6         Phaseolus Lunatus (Green Bean) Seed Extract
 7                                                 NaN
 8                      Limonia Acidissima Wood Powder
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN  ,
     성분코드            표준 성분명                              표준 영문명  \
 0     27             리치추출물      Litchi Chinensis Fruit Extract
 1     28       리토탐니온 칼카룸가루      Lithothamnion Calcareum Powder
 2     29     리튬마그네슘소듐실리케이트   Lithium Magnesium Sodium Silicate
 3     30          리튬스테아레이트                    Lithium Stearate
 4     31  글루티너스리트세아나무껍질추출물       Litsea Glutinosa Bark Extract
 5     32              리파아제                              Lipase
 6     33      리피아 시도이데스잎오일            Lippia Sidoides Leaf Oil
 7     34               구아검  Cyamopsis Tetragonoloba (Guar) Gum
 8     35         유럽피나무꽃추출물       Tilia Europaea Flower Extract
 9     36            마가목추출물             Sorbus Commixta Extract
 10    37        마그네슘글루코네이트                 Magnesium Gluconate
 11    38        마그네슘나이트레이트                   Magnesium Nitrate
 12    39    마그네슘라우레스-8설페이트         Magnesium Laureth-8 Sulfate
 13    40      마그네슘라우레스설페이트           Magnesium Laureth Sulfate

                 구명칭                            구영문명
 0   리치열매추출물|여지열매추출물  Litchi Chinensis Fruit Extract
 1       리토탐니움 칼카룸가루   Lithothamnium Calcarum Powder
 2               NaN                             NaN
 3               NaN                             NaN
 4   리트세아 글루티노사껍질추출물                             NaN
 5               NaN                             NaN
 6               NaN                             NaN
 7               NaN                             NaN
 8            린덴꽃추출물   Tilia Europaea Flower Extract
 9               NaN                             NaN
 10              NaN                             NaN
 11              NaN                             NaN
 12              NaN                             NaN
 13              NaN                             NaN  ,
     성분코드         표준 성분명                        표준 영문명  구명칭  구영문명
 0     41    마그네슘라우릴설페이트      Magnesium Lauryl Sulfate  NaN   NaN
 1     42       마그네슘락테이트             Magnesium Lactate  NaN   NaN
 2     43     마그네슘미리스테이트           Magnesium Myristate  NaN   NaN
 3     44     마그네슘살리실레이트          Magnesium Salicylate  NaN   NaN
 4     45           구아노신                     Guanosine  NaN   NaN
 5     46       마그네슘설페이트             Magnesium Sulfate  NaN   NaN
 6     47     마그네슘스테아레이트            Magnesium Stearate  NaN   NaN
 7     48      마그네슘시트레이트             Magnesium Citrate  NaN   NaN
 8     49      마그네슘실리케이트            Magnesium Silicate  NaN   NaN
 9     50      마그네슘아세테이트             Magnesium Acetate  NaN   NaN
 10    51  마그네슘아스코빌포스페이트  Magnesium Ascorbyl Phosphate  NaN   NaN
 11    52     마그네슘아스파테이트           Magnesium Aspartate  NaN   NaN
 12    53  마그네슘알루미늄실리케이트   Magnesium Aluminum Silicate  NaN   NaN
 13    54       마그네슘옥사이드               Magnesium Oxide  NaN   NaN,
     성분코드                              표준 성분명  \
 0     55                         마그네슘올레스설페이트
 1     56                           구아니딘카보네이트
 2     57                           마그네슘카보네이트
 3     58                    마그네슘카보네이트하이드록사이드
 4     59                           마그네슘클로라이드
 5     60                        마그네슘트라이실리케이트
 6     61                      마그네슘팔미토일글루타메이트
 7     62  마그네슘/포타슘/실리콘/플루오라이드/하이드록사이드/옥\r사이드
 8     63                    마그네슘포타슘플루오로실리케이트
 9     64                            마그네슘피씨에이
 10    65                         마그네슘하이드록사이드
 11    66                             황목련꽃추출물
 12    67                                 구아닌
 13    68                           마누카가지/잎오일

                                                표준 영문명          구명칭  \
 0                             Magnesium Oleth Sulfate          NaN
 1                                 Guanidine Carbonate          NaN
 2                                 Magnesium Carbonate          NaN
 3                       Magnesium Carbonate Hydroxide          NaN
 4                                  Magnesium Chloride          NaN
 5                               Magnesium Trisilicate  마그네슘트리실리케이트
 6                       Magnesium Palmitoyl Glutamate          NaN
 7   Magnesium/Potassium/Silicon/Fluoride/Hydroxide...          NaN
 8                  Magnesium Potassium Fluorosilicate          NaN
 9                                       Magnesium PCA          NaN
 10                                Magnesium Hydroxide          NaN
 11                  Magnolia Acuminata Flower Extract    마그놀리아꽃추출물
 12                                            Guanine          NaN
 13             Leptospermum Scoparium Branch/Leaf Oil          NaN

                                  구영문명
 0                                 NaN
 1                                 NaN
 2                                 NaN
 3                                 NaN
 4                                 NaN
 5               Magnesium Trisilicate
 6                                 NaN
 7                                 NaN
 8                                 NaN
 9                                 NaN
 10                                NaN
 11  Magnolia Acuminata Flower Extract
 12                                NaN
 13                                NaN  ,
     성분코드        표준 성분명                                             표준 영문명  \
 0     69         마늘추출물               Allium Sativum (Garlic) Bulb Extract
 1     70       마데카소사이드                                      Madecassoside
 2     71       마데카식애씨드                                    Madecassic Acid
 3     72       마돈나백합꽃수                       Lilium Candidum Flower Water
 4     73     마돈나백합꽃추출물                     Lilium Candidum Flower Extract
 5     74  마돈나백합비늘줄기추출물                       Lilium Candidum Bulb Extract
 6     75    가시칠엽수껍질추출물  Aesculus Hippocastanum (Horse Chestnut) Bark E...
 7     76     가시칠엽수씨추출물  Aesculus Hippocastanum (Horse Chestnut) Seed E...
 8     77        마뿌리추출물    Dioscorea Oppositifolia (Wild Yam) Root Extract
 9     78       구아바잎추출물                       Psidium Guajava Leaf Extract
 10    79        마시멜로뿌리                           Althaea Officinalis Root
 11    80     마시멜로뿌리추출물                   Althaea Officinalis Root Extract
 12    81   마시멜로잎/뿌리추출물              Althaea Officinalis Leaf/Root Extract
 13    82      마시멜로잎추출물                   Althaea Officinalis Leaf Extract

           구명칭                                               구영문명
 0         NaN                                                NaN
 1         NaN                                                NaN
 2         NaN                                                NaN
 3         NaN                                                NaN
 4         NaN                                                NaN
 5         NaN                                                NaN
 6   마로니에껍질추출물  Aesculus Hippocastanum (Horse Chestnut) Bark E...
 7    마로니에씨추출물  Aesculus Hippocastanum (Horse Chestnut) Seed E...
 8         NaN                                                NaN
 9         NaN                                                NaN
 10        NaN                                                NaN
 11        NaN                                                NaN
 12        NaN                                                NaN
 13        NaN                                                NaN  ,
     성분코드          표준 성분명                             표준 영문명           구명칭  \
 0     83             마이카                               Mica           NaN
 1     84      마이크로코쿠스용해물                 Micrococcus Lysate           NaN
 2     85  마이크로크리스탈린셀룰로오스         Microcrystalline Cellulose           NaN
 3     86     마이크로크리스탈린왁스               Microcrystalline Wax  세라마이크로크리스탈리나
 4     87            삼씨오일           Cannabis Sativa Seed Oil          마인오일
 5     88          쇠비름추출물         Portulaca Oleracea Extract        마치현추출물
 6     89        구아바열매추출물      Psidium Guajava Fruit Extract        구아바추출물
 7     90         퀸즈랜드넛오일    Macadamia Integrifolia Seed Oil      마카다미아씨오일
 8     91       마카다미아씨추출물  Macadamia Ternifolia Seed Extract           NaN
 9     92         마카뿌리추출물      Lepidium Meyenii Root Extract           NaN
 10    93          마테잎추출물   Ilex Paraguariensis Leaf Extract           NaN
 11    94            마텔오일                Myrtus Communis Oil           NaN
 12    95            마텔잎수         Myrtus Communis Leaf Water           NaN
 13    96           마텔추출물            Myrtus Communis Extract           NaN

                                                  구영문명
 0                                                 NaN
 1                                                 NaN
 2                                                 NaN
 3                               Cera Microcristallina
 4                            Cannabis Sativa Seed Oil
 5                          Portulaca Oleracea Extract
 6                       Psidium Guajava Fruit Extract
 7   Macadamia Integrifolia Seed Oil|Macadamia Tern...
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN  ,
     성분코드          표준 성분명                                          표준 영문명  \
 0     97          초마황추출물                          Ephedra Sinica Extract
 1     98              만난                                          Mannan
 2     99          구아이아줄렌                                     Guaiazulene
 3    100             만니톨                                        Mannitol
 4    101      필리핀오렌지껍질오일       Citrus Nobilis (Mandarin Orange) Peel Oil
 5    102     필리핀오렌지껍질추출물   Citrus Nobilis (Mandarin Orange) Peel Extract
 6    103         필리핀오렌지수          Citrus Nobilis (Mandarin Orange) Water
 7    104       필리핀오렌지추출물  Citrus Nobilis (Mandarin Orange) Fruit Extract
 8    105          만델릭애씨드                                   Mandelic Acid
 9    106       만주곰슬껍질추출물                 Pinus Tabuliformis Bark Extract
 10   107         튜베로즈추출물                     Polianthes Tuberosa Extract
 11   108      말굽잔나비버섯추출물            Fomes Officinalis (Mushroom) Extract
 12   109           말라카이트                                       Malachite
 13   110  힙네아 무스키포르미스추출물                      Hypnea Musciformis Extract

            구명칭                                            구영문명
 0        마황추출물                          Ephedra Sinica Extract
 1          NaN                                             NaN
 2          NaN                                             NaN
 3          NaN                                             NaN
 4      만다린껍질오일       Citrus Nobilis (Mandarin Orange) Peel Oil
 5     만다린껍질추출물   Citrus Nobilis (Mandarin Orange) Peel Extract
 6         만다린수          Citrus Nobilis (Mandarin Orange) Water
 7       만다린추출물  Citrus Nobilis (Mandarin Orange) Fruit Extract
 8          NaN                                             NaN
 9    만주곰솔껍질추출물                Pinus Tabulaeformis Bark Extract
 10      만향옥추출물                     Polianthes Tuberosa Extract
 11         NaN                                             NaN
 12         NaN                                             NaN
 13  갈고리가시우무추출물                                             NaN  ,
     성분코드                표준 성분명  \
 0    111  구아하이드록시프로필트라이모늄클로라이드
 1    112              말라카이트추출물
 2    113                말레익애씨드
 3    114          당아욱꽃/잎/줄기추출물
 4    115                당아욱잎가루
 5    116               당아욱잎추출물
 6    117                당아욱추출물
 7    118             말리에이티드콩오일
 8    119            아라비안자스민꽃왁스
 9    120           아라비안자스민꽃추출물
 10   121         아라비안자스민잎세포추출물
 11   122                구절초추출물
 12   123                 말릭애씨드
 13   124                 말미잘자포

                                                표준 영문명                  구명칭  \
 0                Guar Hydroxypropyltrimonium Chloride  구아하이드록시프로필트리모늄클로라이드
 1                                   Malachite Extract                  NaN
 2                                         Maleic Acid                  NaN
 3   Malva Sylvestris (Mallow) Flower/Leaf/Stem Ext...         말로우꽃/잎/줄기추출물
 4               Malva Sylvestris (Mallow) Leaf Powder               말로우잎가루
 5              Malva Sylvestris (Mallow) Leaf Extract              말로우잎추출물
 6                   Malva Sylvestris (Mallow) Extract               말로우추출물
 7                                Maleated Soybean Oil                  NaN
 8                Jasminum Sambac (Jasmine) Flower Wax               말리화꽃왁스
 9            Jasminum Sambac (Jasmine) Flower Extract              말리화꽃추출물
 10        Jasminum Sambac (Jasmine) Leaf Cell Extract            말리화잎세포추출물
 11                    Chrysanthemum Sibiricum Extract               구절초추출물
 12                                         Malic Acid                  NaN
 13                             Sea Anemone Nematocyst                  NaN

                                                  구영문명
 0                Guar Hydroxypropyltrimonium Chloride
 1                                                 NaN
 2                                                 NaN
 3   Malva Sylvestris (Mallow) Flower/Leaf/Stem Ext...
 4               Malva Sylvestris (Mallow) Leaf Powder
 5              Malva Sylvestris (Mallow) Leaf Extract
 6                   Malva Sylvestris (Mallow) Extract
 7                                                 NaN
 8                Jasminum Sambac (Jasmine) Flower Wax
 9            Jasminum Sambac (Jasmine) Flower Extract
 10        Jasminum Sambac (Jasmine) Leaf Cell Extract
 11  Chrysanthemum Sibiricum Extract|Chrysanthemum\...
 12                                                NaN
 13                                                NaN  ,
     성분코드       표준 성분명                                표준 영문명        구명칭  \
 0    125       말토덱스트린                          Maltodextrin        NaN
 1    126    말토바이오닉애씨드                      Maltobionic Acid        NaN
 2    127          말토스                               Maltose        NaN
 3    128  말토실사이클로덱스트린                 Maltosyl Cyclodextrin        NaN
 4    129          말티톨                              Maltitol        NaN
 5    130     말티톨라우레이트                      Maltitol Laurate        NaN
 6    131   망가니즈글루코네이트                   Manganese Gluconate        NaN
 7    132   망가니즈다이옥사이드                     Manganese Dioxide  망가니즈디옥사이드
 8    133     망가니즈바이올렛                      Manganese Violet        NaN
 9    134    망가니즈클로라이드                    Manganese Chloride        NaN
 10   135     망가니즈피씨에이                         Manganese PCA        NaN
 11   136    망고스틴껍질추출물      Garcinia Mangostana Peel Extract        NaN
 12   137          망고씨         Mangifera Indica (Mango) Seed        NaN
 13   138        망고씨버터  Mangifera Indica (Mango) Seed Butter     망고씨드버터

                                     구영문명
 0                                    NaN
 1                                    NaN
 2                                    NaN
 3                                    NaN
 4                                    NaN
 5                                    NaN
 6                                    NaN
 7                      Manganese Dioxide
 8                                    NaN
 9                                    NaN
 10                                   NaN
 11                                   NaN
 12                                   NaN
 13  Mangifera Indica (Mango) Seed Butter  ,

In [7]:
# 1-1
# pd. concat : 리스트에 있는 여러 DataFrame을 하나의 DataFrame으로 합침
ingredients_df = pd.concat(ingredients_list, ignore_index=False)
#ignore_index=False: 이 옵션은 합치는 과정에서 원래의 index를 유지할 것인지를 결정합니다. False로 설정된 경우, 원래 DataFrame들의 index가 그대로 유지됩니다. 만약 True로 설정한다면, index는 리셋되어 0부터 다시 시작됩니다.
ingredients_df
check_01_01(ingredients_df)

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 10 / 100

### **문제 1-2)** 성분사전 DataFrame 내의 Data 수정하기 - 1(15점)
- 이 성분 사전 DataFrame에는 원본에는 없는 '\r' 이 아래와 같이 data 사이에 끼어 있습니다. 이 '\r'을 삭제하세요
<br></br>
    <img src="images/02-1-2-001.png" style="margin:auto" width=700/>
    <img src="images/02-1-2-002.png" style="margin:auto" width=1000/>
<br></br>
    - hint1: '\r'를 대체 할 때 한글('표준 성분명', '구명칭')의 경우 띄어쓰기가 없고, 영어('표준 영문명', '구영문명)의 경우 띄어쓰기를 해야 합니다.
<br></br>
    - hint2: 모든 영문명의 경우 대문자로 시작합니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_02 함수에 입력하여 채점하세요.

In [8]:
ingredients_df.reset_index(drop=True, inplace=True)

In [9]:
# 1-2
ingredients_df['표준 성분명'] = ingredients_df['표준 성분명'].replace('\r', "",regex = True)
ingredients_df['구명칭'] = ingredients_df['구명칭'].replace('\r', "", regex = True)
ingredients_df['표준 영문명'] = ingredients_df['표준 영문명'].replace('\r', " ", regex = True)
ingredients_df['구영문명'] = ingredients_df['구영문명'].replace('\r', " ", regex = True)
check_01_02(ingredients_df)
ingredients_df

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 25 / 100

,성분코드,표준 성분명,표준 영문명,구명칭,구영문명
0,1,가공소금,NaN,NaN,NaN
1,2,가지열매추출물,Solanum Melongena (Eggplant) Fruit Extract,가지추출물,Solanum Melongena (Eggplant) Fruit Extract
2,3,구멍쇠미역추출물,Agarum Cribrosum Extract,구멍쇠미역추출물,Agarum Cribosum Extract
3,4,루핀아미노산,Lupine Amino Acids,NaN,NaN
4,5,류신,Leucine,NaN,NaN
...,...,...,...,...,...
20370,23242,비타민나무열매수,Hippophae Rhamnoides Fruit Water,NaN,NaN
20371,23243,효모/헥사펩타이드-11발효여과추출물,Saccharomyces/Hexapeptide-11 Ferment Filtrate ...,NaN,NaN
20372,23247,약모밀잎소포,NaN,NaN,NaN
20373,23248,삼뿌리수,NaN,NaN,NaN
20374,23249,흑효모/매스틱검추출물발효여과물,NaN,NaN,NaN

### **문제 1-3)** 성분사전 DataFrame 내의 Data 수정하기 - 2(15점)
- pdf를 dataframe으로 전환하면서 일부 누락된 데이터가 있습니다. 아래 cell의 replace_dict는 현재값(key):변경할값(value)의 쌍으로 이루어져 있습니다. 이 replace_dict를 이용하여 성분사전 dataframe '표준 영문명' column의 값을 변경하세요.
<br></br>
    - 참고: replace_dict의 내용만 변경하면 됩니다. 다른 누락사항을 확인하여 변경할 필요는 없습니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_01_03 함수에 입력하여 채점하세요.

In [10]:
replace_dict = {
    'Acetobacter/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitumit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia': 'Acetobacter/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitumit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia Ferment',
    'Saccharomyces/Licorice Root/Rehmannia Glutinosa Root/Angelica Gigas Root/Ophiopogon Japonicus Root/Atractylodes Macrocephala Root/Paeonia Lactiflora Root/Anemarrhena Asphodeloides Root/Fraxinus Excelsior Bark/Asparagus Cochinchinensis/Phellodendron Amurense': 'Saccharomyces/Licorice Root/Rehmannia Glutinosa Root/Angelica Gigas Root/Ophiopogon Japonicus Root/Atractylodes Macrocephala Root/Paeonia Lactiflora Root/Anemarrhena Asphodeloides Root/Fraxinus Excelsior Bark/Asparagus Cochinchinensis/Phellodendron Amurense Bark Ferment Extract',
    'Bacillus/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia': 'Bacillus/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia Ferment',
    'Bifida/Angelica Gigas/Angelica Tenuissima Root/Antler Velvet/Rehmannia Glutinosa Root/Atractylodes Japonica Rhizome/Cnidium Officinale Root/Cordyceps Sinensis/Ledebouriella Seseloides Root/Licorice Root/Paeonia Lactiflora Root/Panax Ginseng': 'Bifida/Angelica Gigas/Angelica Tenuissima Root/Antler Velvet/Rehmannia Glutinosa Root/Atractylodes Japonica Rhizome/Cnidium Officinale Root/Cordyceps Sinensis/Ledebouriella Seseloides Root/Licorice Root/Paeonia Lactiflora Root/Panax Ginseng Root/Phellinus Linteus/Scutellaria Baicalensis Root Ferment',
    'Leuconostoc/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia': 'Leuconostoc/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia Ferment',
    'Saccharomyces/Anemarrhena Asphodeloides Root/Angelica Gigas Root/Asparagus Cochinchinensis/Atractylodes Macrocephala Root/Fraxinus Excelsior Bark/Licorice Root/Ophiopogon Japonicus Root/Paeonia Lactiflora Root/Phellodendron Amurense': 'Saccharomyces/Anemarrhena Asphodeloides Root/Angelica Gigas Root/Asparagus Cochinchinensis/Atractylodes Macrocephala Root/Fraxinus Excelsior Bark/Licorice Root/Ophiopogon Japonicus Root/Paeonia Lactiflora Root/Phellodendron Amurense Bark Ferment Extract',
    'Saccharomyces/Camellia Japonica Flower/Castanea Crenata Shell/Diospyros Kaki Leaf/Paeonia Suffruticosa Root/Rhus Javanica/Sanguisorba Officinalis Root Extract': 'Saccharomyces/Camellia Japonica Flower/Castanea Crenata Shell/Diospyros Kaki Leaf/Paeonia Suffruticosa Root/Rhus Javanica/Sanguisorba Officinalis Root Extract Ferment Filtrate',
    'Lactobacillus/Honeysuckle Flower/Licorice Root/Morus Alba Root/Pueraria Lobata Root/Schisandra Chinensis Fruit/Scutellaria Baicalensis Root/Sophora Japonica Flower': 'Lactobacillus/Honeysuckle Flower/Licorice Root/Morus Alba Root/Pueraria Lobata Root/Schizandra Chinensis Fruit/Scutellaria Baicalensis Root/Sophora Japonica Flower Extract Ferment Filtrate',
    'Lactobacillus/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/Cinnamomum Cassia': 'Lactobacillus/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/Cinnamomum Cassia Ramulus Bark Ferment Filtrate',
    'Saccharomyces/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia': 'Saccharomyces/Lycium Chinense Fruit/Rehmannia Glutinosa Root/Cuscuta Chinensis Fruit/Cistanche Deserticola/Zanthoxylum Piperitum Fruit/Chrysanthemum Morifolium Fruit/Poria Cocos/ Cinnamomum Cassia Ferment',
}

In [11]:
# 1-3
ingredients_df['표준 영문명'] = ingredients_df['표준 영문명'].replace(replace_dict)
check_01_03(ingredients_df)
ingredients_df

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 40 / 100

,성분코드,표준 성분명,표준 영문명,구명칭,구영문명
0,1,가공소금,NaN,NaN,NaN
1,2,가지열매추출물,Solanum Melongena (Eggplant) Fruit Extract,가지추출물,Solanum Melongena (Eggplant) Fruit Extract
2,3,구멍쇠미역추출물,Agarum Cribrosum Extract,구멍쇠미역추출물,Agarum Cribosum Extract
3,4,루핀아미노산,Lupine Amino Acids,NaN,NaN
4,5,류신,Leucine,NaN,NaN
...,...,...,...,...,...
20370,23242,비타민나무열매수,Hippophae Rhamnoides Fruit Water,NaN,NaN
20371,23243,효모/헥사펩타이드-11발효여과추출물,Saccharomyces/Hexapeptide-11 Ferment Filtrate ...,NaN,NaN
20372,23247,약모밀잎소포,NaN,NaN,NaN
20373,23248,삼뿌리수,NaN,NaN,NaN
20374,23249,흑효모/매스틱검추출물발효여과물,NaN,NaN,NaN

## 2단계: Target Data 수정하기
***

### **문제 2-1)** Target DataFrame 중 Ingredients Column 내의 Data 수정하기(20점)
- Kaggle에서 가져오는 데이터는 수정을 필요로 하는 경우가 있습니다. 제시된 Target DataFrame 또한 성분사전과 다른 표현을 쓰는 경우가 있어 해당 내용에 대해 수정을 하고자 합니다. 다음 조건에 맞게 Ingredients Column의 데이터를 수정하세요.
<br></br>
    - 조건1: 맨 끝에 마침표('.')가 있다면 마지막 마침표만 제거하세요
        - ex) 'Algae (Seaweed) Extract. Sea Salt.' -> 'Algae (Seaweed) Extract. Sea Salt'
<br></br>
    - 조건2: '. May Contain'를 포함하고 있다면, '. May Contain' 이후의 데이터를 제거하세요
        - ex) 'Algae (Seaweed) Extract. May Contain: Sea Salt, Fragrance' -> 'Algae (Seaweed) Extract'
<br></br>
    - 조건3: 아래의 replace_str_dict는 현재값(key):변경할값(value)의 쌍으로 이루어져 있습니다. 이 replace_str_dict를 이용하여 데이터를 변경하세요
        - 참고: replace_str_dict의 내용만 변경하면 됩니다. 다른 누락사항을 확인하여 변경할 필요는 없습니다.
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_01 함수에 입력하여 채점하세요.

In [12]:
replace_str_dict = {
    'Algae (Seaweed) Extract': 'Algae Extract',
    'Citrus Aurantifolia (Lime) Extract': 'Citrus Aurantifolia (Lime) Fruit Extract',
    'Eucalyptus Globulus (Eucalyptus) Leaf Oil': 'Eucalyptus Globulus Leaf Oil',
    'Galactomyces Ferment Filtrate (Pitera)': 'Galactomyces Ferment Filtrate',
    'Bacillus/Soybean/ Folic Acid Ferment Extract': 'Bacillus/Folic Acid/Soybean Ferment Extract',
    'Butyrospermum Parkii (Shea Butter)': 'Butyrospermum Parkii (Shea) Butter',
    'Sea Salt/Maris Sal/Sel Marin': 'Sea Salt',
    'Parfum/Fragrance': 'Fragrance|Perfume|Parfum',
    ', Fragrance': ', Fragrance|Perfume|Parfum',
    }

In [13]:
# 2-1

df_target['Ingredients'] = df_target['Ingredients'].replace('\.\,',',', regex=True)
df_target['Ingredients'] = df_target['Ingredients'].replace('\.$','',regex=True)
df_target['Ingredients'] = df_target['Ingredients'].replace('\. May Contain.*', '',regex=True)
df_target['Ingredients'] = df_target['Ingredients'].replace(replace_str_dict)
for key, value in replace_str_dict.items():
    for idx, row in df_target.iterrows():
        re_place = df_target.loc[idx, "Ingredients"].replace(key, value)
        df_target.loc[idx, "Ingredients"] = re_place
check_02_01(df_target)
df_target

정답입니다! 20점 누적 되었습니다!
현재 누적 점수: 60 / 100

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae Extract, Mineral Oil, Petrolatum, Glycer...",1,1,1,1,1
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate, Butylene Glycol...",1,1,1,1,1
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae Extract, Cyclopentasiloxane, Petrolatum,...",1,1,1,1,1
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1

### **문제 2-2)** Target DataFrame 중 'Ingredients' Column Data 변환하기(10점)
- 다음 조건에 맞게 앞서 수정한 'Ingredients' Column의 데이터를 변환하여 'Ingredients List' Column에 입력하세요.
<br></br>
    - 조건1: 'Ingredients' Column의 각 데이터를 ', '(쉼표+띄어쓰기)로 분리하여 List로 변환하세요
        - ex) '  Algae (Seaweed) Extract,  Sea Salt  ' -> ['  Algae (Seaweed) Extract', ' Sea Salt  ']
<br></br>
    - 조건2: 조건1에서 변경한 list의 각 Element 앞뒤의 공백이 있다면 공백을 삭제하세요
        - ex) ['  Algae (Seaweed) Extract', ' Sea Salt  '] -> ['Algae (Seaweed) Extract', 'Sea Salt']
<br></br>
    - 조건3: 'Ingredients List' Column을 새로 생성하여 조건1과 조건2에서 만든 list를 각 행에 맞게 입력하세요
<br></br>
- 완료 후 결과 dataframe 변수를 check_02_02 함수에 입력하여 채점하세요.

In [14]:
# 2-2
ingredients_list = []
for j in range(0, len(df_target['Ingredients'])):
    ingredient = df_target['Ingredients'][j].split(', ')
    for n in range(0, len(ingredient)):
        ingredient[n] = ingredient[n].strip()
    ingredients_list.append(ingredient)
df_target['Ingredients List'] = ingredients_list
check_02_02(df_target)
df_target

정답입니다! 10점 누적 되었습니다!
현재 누적 점수: 70 / 100

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive,Ingredients List
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae Extract, Mineral Oil, Petrolatum, Glycer...",1,1,1,1,1,"[Algae Extract, Mineral Oil, Petrolatum, Glyce..."
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate, Butylene Glycol...",1,1,1,1,1,"[Galactomyces Ferment Filtrate, Butylene Glyco..."
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0,"[Water, Dicaprylyl Carbonate, Glycerin, Cetear..."
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae Extract, Cyclopentasiloxane, Petrolatum,...",1,1,1,1,1,"[Algae Extract, Cyclopentasiloxane, Petrolatum..."
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1,"[Water, Snail Secretion Filtrate, Phenyl Trime..."

## 3단계: 성분사전(Ingredients Dictionary)을 이용하여 Mapping하기
***

### **문제 3-1)** Target DataFrame 의 'Ingredients List' Column를 Mapping하여 'Code List' Column 만들기(15점)
- (아래 예시를 참고)성분사전(Ingredients Dictionary)를 이용하여 Target DataFrame의 'Ingredients List'를 각 성분에 Mapping되는 'Code List'로 만들고, 'Code List' Column을 만들어 Code List를 각 행에 맞게 입력하세요.
<br></br>
    <img src="images/02-3-1-001.png" style="margin:auto" width=300/>
    <img src="images/02-3-1-002.png" style="margin:auto" width=450/>
<br></br>
    - 조건1: Ingredients List에 대응하는 Code List의 순서는 같아야 합니다.
<br></br>
<br></br>
    - hint1: '표준 영문명'에서 찾지 못한다면 '구영문명'으로도 찾아보세요
<br></br>
    - hint2: 대문자-소문자 차이가 있을 수 있습니다.
<br></br>
    - 참고: 'Code'는 성분사전(Ingredients Dictionary)의 '성분코드'를 의미합니다.(Index가 아닙니다)
<br></br>
- 완료 후 결과 dataframe 변수를 check_03_01 함수에 입력하여 채점하세요.

In [15]:
ingredients_df

,성분코드,표준 성분명,표준 영문명,구명칭,구영문명
0,1,가공소금,NaN,NaN,NaN
1,2,가지열매추출물,Solanum Melongena (Eggplant) Fruit Extract,가지추출물,Solanum Melongena (Eggplant) Fruit Extract
2,3,구멍쇠미역추출물,Agarum Cribrosum Extract,구멍쇠미역추출물,Agarum Cribosum Extract
3,4,루핀아미노산,Lupine Amino Acids,NaN,NaN
4,5,류신,Leucine,NaN,NaN
...,...,...,...,...,...
20370,23242,비타민나무열매수,Hippophae Rhamnoides Fruit Water,NaN,NaN
20371,23243,효모/헥사펩타이드-11발효여과추출물,Saccharomyces/Hexapeptide-11 Ferment Filtrate ...,NaN,NaN
20372,23247,약모밀잎소포,NaN,NaN,NaN
20373,23248,삼뿌리수,NaN,NaN,NaN
20374,23249,흑효모/매스틱검추출물발효여과물,NaN,NaN,NaN

In [16]:
df_target

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive,Ingredients List
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae Extract, Mineral Oil, Petrolatum, Glycer...",1,1,1,1,1,"[Algae Extract, Mineral Oil, Petrolatum, Glyce..."
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate, Butylene Glycol...",1,1,1,1,1,"[Galactomyces Ferment Filtrate, Butylene Glyco..."
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0,"[Water, Dicaprylyl Carbonate, Glycerin, Cetear..."
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae Extract, Cyclopentasiloxane, Petrolatum,...",1,1,1,1,1,"[Algae Extract, Cyclopentasiloxane, Petrolatum..."
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1,"[Water, Snail Secretion Filtrate, Phenyl Trime..."

In [17]:
# 3-1
def map_code_list(ingredients_list):
    code_list = []
    for i in ingredients_list:
        code = ingredients_df[(i.lower() == ingredients_df['표준 영문명'].str.lower()) | (i.lower() == ingredients_df['구영문명'].str.lower())]['성분코드'].values
        if len(code) > 0:
            code_list.append(code[0])
        else:
            code_list.append(None)
    return code_list
    
new_code_list = []
for n in range(0, len(ingredients_list)):
    new_code_list.append(map_code_list(ingredients_list[n]))
    
df_target['Code List'] = new_code_list

check_03_01(df_target)
df_target

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 85 / 100

,Label,Brand,Name,Price,Rank,Ingredients,Combination,Dry,Normal,Oily,Sensitive,Ingredients List,Code List
0,Moisturizer,LA MER,Crème de la Mer,175,4.1,"Algae Extract, Mineral Oil, Petrolatum, Glycer...",1,1,1,1,1,"[Algae Extract, Mineral Oil, Petrolatum, Glyce...","[979, 317, 3602, 1013, 2547, 86, 5299, 5416, 2..."
1,Moisturizer,SK-II,Facial Treatment Essence,179,4.1,"Galactomyces Ferment Filtrate, Butylene Glycol...",1,1,1,1,1,"[Galactomyces Ferment Filtrate, Butylene Glyco...","[6377, 586, 3635, 2700, 1116, 213, 1299]"
2,Moisturizer,DRUNK ELEPHANT,Protini™ Polypeptide Cream,68,4.4,"Water, Dicaprylyl Carbonate, Glycerin, Ceteary...",1,1,1,1,0,"[Water, Dicaprylyl Carbonate, Glycerin, Cetear...","[2700, 5218, 1013, 974, 976, 1290, 677, 7177, ..."
3,Moisturizer,LA MER,The Moisturizing Soft Cream,175,3.8,"Algae Extract, Cyclopentasiloxane, Petrolatum,...",1,1,1,1,1,"[Algae Extract, Cyclopentasiloxane, Petrolatum...","[979, 769, 3602, 1057, 3586, 586, 4566, 3087, ..."
4,Moisturizer,IT COSMETICS,Your Skin But Better™ CC+™ Cream with SPF 50+,38,4.1,"Water, Snail Secretion Filtrate, Phenyl Trimet...",1,1,1,1,1,"[Water, Snail Secretion Filtrate, Phenyl Trime...","[2700, 6319, 3586, 4512, 586, 587, 387, 606, 1..."

### **문제 3-2)** 다음 조건을 만족하는 code들을 찾아 그 code들에 해당하는 DataFrame을 구하세요(15점)
- (아래 예시를 참고) Target DataFrame의 Code List를 **각 행 내에서 중복 없이** 모두 합쳐 두 번 나온 수를 오름차순으로 정렬하고, 첫번째부터 다섯번째까지의 수들을 찾아 성분사전(Ingredients Dictionary)를 이용하여 해당 Code들의 DataFrame을 구하세요.
<br></br>
    - 예시 DataFrame
<br></br>
    <img src="images/02-3-2-001.png" style="margin:auto" width=300/>
<br></br>
    - 이 DataFrame에서 나타난 Code 중 **각 행 내에서 중복 없이** 두 번 나온 Code는 [3, 9, 23, 34, 57, 234] 이고, 이 중 오름차순으로 첫번째부터 다섯번째까지의 수는 [3, 9, 23, 34, 57] 입니다.
        - 참고
            - '3'의 경우 2번 행과 3번 행에서 나왔습니다.
            - 0번 행의 '12'의 경우 중복하여 나왔으므로, 한 번 나온 것으로 count 합니다.
<br></br>
    - 성분사전(Ingredients Dictionary)에서 해당 code들의 DataFrame은 아래와 같습니다.
<br></br>
    <img src="images/02-3-2-002.png" style="margin:auto" width=600/>
<br></br>
    - 조건1: 중복 code는 없어야 합니다.
<br></br>
    - 조건2: '두' 번 나온 수, 오름차순, 첫번째부터 다섯번째까지 다시 한번 확인하세요.
<br></br>
<br></br>
    - hint1: sorted(list, key=lambda x: func(x))
<br></br>
    - hint2: set()
<br></br>
    - hint3: list.count()
<br></br>
<br></br>
    - 참고: 'Code'는 성분사전(Ingredients Dictionary)의 '성분코드'를 의미합니다.(Index가 아닙니다)
<br></br>
- 완료 후 결과 dataframe 변수를 check_03_02 함수에 입력하여 채점하세요.

In [18]:
# 3-2
tmp_list = []
for n in range(0, len(df_target['Code List'])):
    for j in set(df_target['Code List'][n]):
        tmp_list.append(j)

count_list = []
for i in tmp_list:
    if tmp_list.count(i) == 2:
        count_list.append(i)
count_list.sort()
count_list = count_list[::2]

result_df = ingredients_df[ingredients_df['성분코드'].isin(count_list[0:5])]
check_03_02(result_df)
result_df

정답입니다! 15점 누적 되었습니다!
현재 누적 점수: 100 / 100

     성분코드      표준 성분명               표준 영문명       구명칭            구영문명
8       9         리날룰             Linalool       NaN             NaN
19     20         리모넨             Limonene       NaN             NaN
36     37  마그네슘글루코네이트  Magnesium Gluconate       NaN             NaN
45     46    마그네슘설페이트    Magnesium Sulfate       NaN             NaN
760   761    사이아노코발아민       Cyanocobalamin  사이아노코발라민  Cyanocobalamin

***

### 🎊 문제가 끝났습니다. 제출양식과 일정에 맞춰 제출해주시기를 바랍니다!

### 제출양식
- 이 파일은 EDA TEST 2회차 노트북입니다. 따라서 제출시 파일명은 아래와 같습니다.
- [DS]edalvtest_02_yourname.ipynb

***

# 문의사항 및 의견이 있는 경우 작성해주세요.